name: ROCm GPU CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the rocm-main branch
  push:
    branches:
      - rocm-main
  pull_request:
    branches:
      - rocm-main

jobs:
  test-docker-container:
    runs-on: mi-250
    container:
      image: rocm/dev-ubuntu-22.04:6.2.4
    steps:
      - run: echo hello
      - run: rocm-smi
  build-docker: # strategy and matrix come here 
    runs-on:  mi-250
    container:
      image: rocm/dev-ubuntu-22.04:6.2.4
    env:
      ROCM_VERSION: 6.2.4
      #WORKSPACE_DIR: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
    steps:
      - name: Print Environment Variables
        run: printenv
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        #with:
        #  path: $WORKSPACE_DIR
      - name: Fetch Docker image
        run: docker pull rocm/dev-ubuntu-22.04:$ROCM_VERSION
      - name: Build JAX
        run: |
          #pwd
          #cd ./$WORKSPACE_DIR
          #pwd
          #docker run 
          #./build/rocm/ci_build.sh --runtime --rocm_version 6.1.3 --keep_image --py_version 3.10 --use_clang true --dockerfile build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
          python3 build/build.py build --rocm_path=/opt/rocm-$ROCM_VERSION --rocm_version=60 --use_clang=True --clang_path=/opt/rocm-$ROCM_VERSION/llvm/bin/clang
      - name: Archive jax wheels
        uses: actions/upload-artifact@v4
        with:
          name: rocm_jax_r6_1_3_py3_10_id${{ github.run_id }}
          path: ./${{ github.sha }}/wheelhouse/*.whl
      - name: Detect GPUs
        run: |
          docker run \
            --group-add video \
            $RENDER_DEVICES \
            --cap-add=SYS_PTRACE \
            --security-opt seccomp=unconfined \
            --shm-size=64G \
            rocm/rocm-terminal rocm-smi
      - name: Run tests
        env: 
          DOCKER_IMG_NAME: rocm_jax_r6_1_3_py3_10_id${{ github.run_id }}
        run: |
          ./${{ github.sha }}/build/rocm/ci_build test ${DOCKER_IMG_NAME}

