name: Sync rocm/jax with jax-ml/jax
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 12 * * *' # Runs every day
jobs:
  upstream_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: |
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
      - run: |
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
      - run: |
          docker run -t --rm -v$HOME/.ssh:/root/.ssh -v $HOME/.git-credentials:/root/.git-credentials -v $GITHUB_WORKSPACE/build/rocm:/data -e COPYBARA_CONFIG=/data/copy.bara.sky sharelatex/copybara bash -c "git config --global user.name jaxbara; git config --global user.email jaxbara@amd.com; copybara"
