name: ROCM CI

on: [push]

jobs:
  build-docker: # strategy and matrix come here 
    runs-on:  mi-250
    steps:
      - name: Print Environment Variables
        run: printenv
      - uses: actions/checkout@v4
      - name: Build Docker 
        env: 
          BUILD_TAG: rocm_jax_r6_1_3_py3_10_id${{ github.run_id }}
          # XLA_CLONE_DIR: 
        run: |
          ./build/rocm/ci_build.sh --rocm_version 6.1.3 \
          --keep_image --py_version 3.10 
      - cleanup: Remove workspace artifacts
        if: always()
        run: rm -rf ${{ github.workspace }}

      
#       - name: Try rocm-smi
#         run: |
#           docker run \
#             --group-add video \
#             $RENDER_DEVICES \
#             --cap-add=SYS_PTRACE \
#             --security-opt seccomp=unconfined \
#             --shm-size=64G \
#             rocm/rocm-terminal rocm-smi