name: ROCm GPU CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the rocm-main branch
  push:
    branches:
      - rocm-main
  pull_request:
    branches:
      - rocm-main

jobs:
  test-docker-container:
    runs-on: mi-250
    container:
      image: rocm/dev-ubuntu-22.04:6.2.4
    steps:
      - run: echo hello
      - run: rocm-smi
  build-docker: # strategy and matrix come here 
    runs-on:  mi-250
    container:
      image: rocm/dev-ubuntu-22.04:6.2.4
      options:
        group-add: video
        cap-add: SYS_PTRACE
        security-opt: seccomp=unconfined
        shm-size: 64G
    env:
      ROCM_VERSION: 6.2.4
      #WORKSPACE_DIR: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
    steps:
      - name: Print system info
        run: |
          printenv
          rocm-smi
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        #with:
        #  path: $WORKSPACE_DIR
      - name: Build JAX
        run: |
          python3 build/build.py build --wheels=jaxlib,jax-rocm-plugin,jax-rocm-pjrt --python_version=3.10 --rocm_path=/opt/rocm-$ROCM_VERSION --rocm_version=60 --use_clang=True --clang_path=/opt/rocm-$ROCM_VERSION/llvm/bin/clang
      #- name: Archive jax wheels
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: rocm_jax_r6_1_3_py3_10_id${{ github.run_id }}
      #    path: ./dist/*.whl
      #- name: Detect GPUs
      #  run: |
      #    rocm-smi
      #    docker run \
      #      --group-add video \
      #      $RENDER_DEVICES \
      #      --cap-add=SYS_PTRACE \
      #      --security-opt seccomp=unconfined \
      #      --shm-size=64G \
      #      rocm/rocm-terminal rocm-smi
      - name: Run tests
        run: |
          #./${{ github.sha }}/build/rocm/ci_build test ${DOCKER_IMG_NAME}
          python3 build/rocm/ci_build test

