name: ROCm GPU CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the rocm-main branch
  push:
    branches:
      - rocm-main
  pull_request:
    branches:
      - rocm-main

jobs:
  create-build-image:
    runs-on: mi-250
    env:
      ROCM_VERSION: "6.2.4"
      WORKSPACE_DIR: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
    steps:
      - run: echo Add me later
  build-docker: # strategy and matrix come here 
    runs-on:  mi-250
    #container:
    #  image: rocm/dev-ubuntu-22.04:6.2.4
    #  options: --device=/dev/kfd --device=/dev/dri --group-add=video --cap-add=SYS_PTRACE --security-opt=seccomp=unconfined
    env:
      PYTHON_VERSION: "3.10"
      ROCM_VERSION: "6.2.4"
      WORKSPACE_DIR: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
    steps:
      - name: Print system info
        run: |
          printenv
          rocm-smi
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          path: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
       - name: Set repo ownership
         run: |
           # this is to fix GIT not liking owner of the checkout dir
           chown -R $(id -u):$(id -g) $WORKSPACE_DIR
      - name: Build JAX
        run: |
          pwd
          ls
          cd $WORKSPACE_DIR
          pwd
          ./build/rocm/ci_build.sh --runtime --rocm_version $ROCM_VERSION --keep_image --py_version $PYTHON_VERSION --use_clang true
      #- name: Archive jax wheels
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: rocm_jax_r6_1_3_py3_10_id${{ github.run_id }}
      #    path: ./dist/*.whl
      #- name: Detect GPUs
      #  run: |
      #    rocm-smi
      #    docker run \
      #      --group-add video \
      #      $RENDER_DEVICES \
      #      --cap-add=SYS_PTRACE \
      #      --security-opt seccomp=unconfined \
      #      --shm-size=64G \
      #      rocm/rocm-terminal rocm-smi
      - name: Run tests
        run: |
          #./${{ github.sha }}/build/rocm/ci_build test ${DOCKER_IMG_NAME}
          cd $WORKSPACE_DIR
          python3 build/rocm/ci_build test

