name: Print Environment Variables

on: [push]

jobs:
  print-env:
    runs-on: mi-250
    steps:
      - name: Print Environment Variables
        run: printenv
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Try rocm-smi
        run: |
          docker run \
            --group-add video \
            $RENDER_DEVICES \
            --cap-add=SYS_PTRACE \
            --security-opt seccomp=unconfined \
            --shm-size=64G \
            rocm/rocm-terminal rocm-smi