name: Sync rocm/jax with jax-ml/jax
on:
  workflow_dispatch:
  pull_request:
  schedule: 
    - cron: '0 12 * * *' # Runs every day
jobs:
  upstream_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: |
          docker run -t --rm -v$HOME/.ssh:/root/.ssh -v $HOME/.git-credentials:/root/.git-credentials -v $GITHUB_WORKSPACE/copy.bara.sky:/data/copy.bara.sky -e COPYBARA_CONFIG=/data/copy.bara.sky sharelatex/copybara bash -c "git config --global user.name jaxbara; git config --global user.email jaxbara@amd.com; copybara"
