name: Print Environment Variables

on: [push]

jobs:
  print-env:
    runs-on: arc-runner-set-rocm-gpu
    steps:
      - name: Print Environment Variables
        run: printenv   
      - name: Try rocm-smi
        run: |
          docker run \
            --device=/dev/kfd --device=/dev/dri \
            --group-add video \
            --cap-add=SYS_PTRACE \
            --security-opt seccomp=unconfined \
            --shm-size=64G \
            rocm/rocm-terminal rocm-smi
