# CI - Wheel Tests (Nightly/Release) - ROCm only (TEST BRANCH)
#
# Stripped-down version for testing S3 wheel download changes.
# Only runs ROCm tests with 'latest' S3 resolution.

name: CI - Wheel Tests (Nightly/Release)

on:
  workflow_dispatch:
    inputs:
      gcs_download_uri:
        description: "GCS location URI from where the artifacts should be downloaded"
        required: true
        default: 'gs://jax-nightly-artifacts/latest'
        type: string
      skip-download-jaxlib-and-plugins-from-gcs:
        description: "Whether to download only the jax wheel from GCS (e.g for testing a jax only release)"
        required: true
        default: '0'
        type: string
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection? (yes/no)'
        required: false
        default: 'no'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: {}

env:
  UV_DEFAULT_INDEX: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"

jobs:
  run-pytest-rocm:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/pytest_rocm.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-64-1gpu-amd", "linux-x86-64-4gpu-amd", "linux-x86-64-8gpu-amd"]
          python: ["3.11", "3.12", "3.13", "3.14"]
          rocm: [
            {version: "7.2.0", tag: "rocm720"},
          ]
    name: "Pytest ROCm (JAX artifacts version = ${{ startsWith(github.ref_name, 'release/') && 'latest release' || 'nightly' }})"
    with:
      runner: ${{ matrix.runner }}
      python: ${{ matrix.python }}
      rocm-version: ${{ matrix.rocm.version }}
      rocm-tag: ${{ matrix.rocm.tag }}
      jaxlib-version: "head"
      skip-download-jaxlib-and-plugins-from-gcs: ${{inputs.skip-download-jaxlib-and-plugins-from-gcs}}
      gcs_download_uri: ${{inputs.gcs_download_uri}}

  run-bazel-test-rocm:
    uses: ./.github/workflows/bazel_rocm.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-64-1gpu-amd"]
          python: ["3.11", "3.12", "3.13", "3.13-nogil", "3.14", "3.14-nogil"]
          rocm-version: [7]
          enable-x64: [0]
    name: "Bazel ROCm Non-RBE with ${{ format('{0}', 'build_jaxlib=false') }}"
    with:
      runner: ${{ matrix.runner }}
      python: ${{ matrix.python }}
      rocm-version: ${{ matrix.rocm-version }}
      enable-x64:  ${{ matrix.enable-x64 }}
      gcs_download_uri: ${{inputs.gcs_download_uri}}
      halt-for-connection: ${{inputs.halt-for-connection}}
      build_jaxlib: "false"
      build_jax: "false"
      jaxlib-version: "head"
      write_to_bazel_remote_cache: 1
      run_multiaccelerator_tests: "true"
      clone_main_xla: 0
