# CI - Wheel Tests (Continuous)
#
# This workflow builds JAX artifacts and runs CPU/TPU/CUDA/ROCm tests.
#
# It orchestrates the following:
# 1. build-jaxlib-artifact: Calls the `build_artifacts.yml` workflow to build jaxlib and
#                           uploads it to a GCS bucket.
# 2. run-pytest-cpu:        Calls the `pytest_cpu.yml` workflow which downloads the jaxlib wheel
#                           that was built in the previous step and runs CPU tests.
# 3. build-cuda-artifacts:  Calls the `build_artifacts.yml` workflow to build CUDA artifacts and
#                           uploads them to a GCS bucket.
# 4. run-bazel-test-cpu-py-import: Calls the `bazel_cpu_rbe.yml` workflow which
#                           runs Bazel CPU tests with py_import on RBE.
# 5. run-bazel-test-cuda-py-import: Calls the `bazel_cuda.yml` workflow which
#                           runs Bazel CUDA tests with py_import on non-RBE.
# 6. run-pytest-cuda:       Calls the `pytest_cuda.yml` workflow which downloads the jaxlib and CUDA
#                           artifacts that were built in the previous steps and runs the CUDA tests.
# 7. run-bazel-test-cuda:   Calls the `bazel_cuda.yml` workflow which downloads the jaxlib
#                           and CUDA artifacts that were built in the previous steps and runs the
#                           CUDA tests using Bazel.
# 8. run-pytest-tpu:        Calls the `pytest_tpu.yml` workflow which downloads the jaxlib wheel
#                           that was built in the previous step and runs TPU tests.
# 9. run-bazel-test-tpu:    Calls the `bazel_test_tpu.yml` workflow which
#                           runs Bazel TPU tests with py_import.
# 10. build-rocm-artifacts: Calls the `build_rocm_artifacts.yml` workflow to build ROCm plugin/pjrt
#                           wheels and uploads them to an S3 bucket.
# 11. run-pytest-rocm:      Calls the `pytest_rocm.yml` workflow which downloads the jaxlib and
#                           ROCm artifacts and runs the ROCm tests.
# 12. run-bazel-test-rocm:  Calls the `bazel_rocm.yml` workflow which runs the ROCm Bazel tests.

name: CI - Wheel Tests (Continuous)
permissions:
  id-token: write
  contents: read
  actions: read

on:
  schedule:
    - cron: "0 */3 * * *" # Run once every 3 hours
  workflow_dispatch: # allows triggering the workflow run manually

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') && github.ref != 'main' }}

jobs:

  build-rocm-artifacts:
    uses: ./.github/workflows/build_rocm_artifacts.yml
    permissions:
      id-token: write
      contents: read
      actions: read
    strategy:
        fail-fast: false
        matrix:
          runner: ["linux-x86-64-1gpu-amd"]
          artifact: ["jax-rocm-plugin", "jax-rocm-pjrt"]
          python: ["3.11", "3.12", "3.13", "3.14"]
          rocm-version: ["7"]
          exclude:
            - artifact: "jax-rocm-pjrt"
              python: "3.12"
            - artifact: "jax-rocm-pjrt"
              python: "3.13"
            - artifact: "jax-rocm-pjrt"
              python: "3.14"
    name: "Build ${{ format('{0}', 'ROCm') }} artifacts"
    with:
      runner: ${{ matrix.runner }}
      artifact: ${{ matrix.artifact }}
      python: ${{ matrix.python }}
      rocm-version: ${{ matrix.rocm-version }}
      clone_main_xla: 1
      upload_artifacts_to_s3: true
      s3_upload_uri: 's3://jax-ci-amd/rocm-wheels/wheel-tests-continuous/${{ github.run_number }}/${{ github.run_attempt }}'


