# CI - Wheel Tests (Nightly/Release)
#
# This workflow is used to test the JAX wheels that were built by internal CI jobs.
#
# 1. run-pytest-cpu:  Calls the `pytest_cpu.yml` workflow which downloads the JAX wheels that were
#                     built by internal CI jobs and runs CPU tests.
# 2. run-bazel-test-cpu:  Calls the `bazel_cpu.yml` workflow which downloads the
#                     JAX wheels that were built by internal CI jobs and runs Bazel CPU tests.
# 3. run-pytest-cuda: Calls the `pytest_cuda.yml` workflow which downloads the JAX wheels that were
#                     built by internal CI jobs and runs CUDA tests.
# 4. run-bazel-test-cuda: Calls the `bazel_cuda.yml` workflow which downloads the JAX wheels
#                     that were built by internal CI jobs and runs Bazel CUDA tests.
# 5. run-pytest-rocm: Calls the `pytest_rocm.yml` workflow which downloads the JAX wheels and
#                     ROCm plugins from PyPI/GitHub releases and runs ROCm tests.
# 6. run-pytest-tpu: Calls the `pytest_tpu.yml` workflow which downloads the JAX wheels that were
#                    built by internal CI jobs and runs TPU tests.
# 7. run-bazel-test-tpu: Calls the `bazel_test_tpu.yml` workflow which downloads the JAX wheels that
#                        were built by internal CI jobs and runs Bazel TPU tests.
# 8. verify-release-wheels-install: Verifies that JAX's release wheels can be installed.
name: CI - Wheel Tests (Nightly/Release)

on:
  workflow_dispatch:
    inputs:
      gcs_download_uri:
        description: "GCS location URI from where the artifacts should be downloaded"
        required: true
        default: 'gs://jax-nightly-artifacts/latest'
        type: string
      skip-download-jaxlib-and-cuda-plugins-from-gcs:
        description: "Whether to download only the jax wheel from GCS (e.g for testing a jax only release)"
        required: true
        default: '0'
        type: string
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection? (yes/no)'
        required: false
        default: 'no'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: {}

env:
  UV_DEFAULT_INDEX: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"

jobs:
  run-pytest-rocm:
    uses: ./.github/workflows/pytest_rocm.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-64-1gpu-amd", "linux-x86-64-4gpu-amd"]
          python: ["3.11", "3.12"]
          rocm: [
            {version: "7.2.0", tag: "rocm720"},
          ]
          ubuntu-version: ["22", "24"]
          exclude:
            # TODO: decouple ubuntu version and python version.
            # Match python version with ubuntu version.
            - python: "3.11"
              ubuntu-version: "24"
            - python: "3.12"
              ubuntu-version: "22"
    name: "Pytest ROCm (JAX artifacts version = ${{ startsWith(github.ref_name, 'release/') && 'latest release' || 'nightly' }})"
    with:
      runner: ${{ matrix.runner }}
      python: ${{ matrix.python }}
      ubuntu-version: ${{ matrix.ubuntu-version }}
      rocm-version: ${{ matrix.rocm.version }}
      rocm-tag: ${{ matrix.rocm.tag }}
      jax-version: "0.9.0"
      jaxlib-version: "github_release"
      github-release-tag: "rocm-jax-v0.9.0-rc"
      skip-download-jaxlib-and-rocm-plugins: "0"
      download-jax-from-pypi: "1"
